// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Attachment = { id: string, name: string, mime: string, size: number, 
/**
 * Download path, relative to the server's HTTP origin.
 */
url: string, 
/**
 * Pixel size, for images.
 */
width?: number | null, height?: number | null, };
