// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Ban = { id: number, uid?: string | null, ip?: string | null, 
/**
 * Nickname at the time of the ban.
 */
nickname: string, reason?: string | null, by: string, created_at: number, expires_at?: number | null, };
