// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bans an online client (by session) or a known member (by uid).
 */
export type BanCreate = { client?: number | null, uid?: string | null, 
/**
 * Also ban the client's IP address (online clients only).
 */
ip: boolean, 
/**
 * Seconds; absent means permanent.
 */
duration?: number | null, reason?: string | null, };
