// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BanNotice = { by: string, reason?: string | null, 
/**
 * Unix ms; absent for a permanent ban.
 */
until?: number | null, };
