// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Channel = { id: number, parent: number | null, name: string, topic: string, position: number, has_password: boolean, max_clients: number | null, };
