// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Absent fields stay unchanged. `password: ""` removes the password,
 * `max_clients: 0` removes the limit,
 * `parent: null` with `move_to_root: true` moves the channel to the top level.
 */
export type ChannelUpdate = { channel: number, name?: string | null, topic?: string | null, password?: string | null, max_clients?: number | null, parent?: number | null, move_to_root: boolean, 
/**
 * Sort key among siblings; lower comes first.
 */
position?: number | null, };
