// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatTarget } from "./ChatTarget";

export type ChatMessage = { id: number, target: ChatTarget, author: number, author_uid: string, author_name: string, text: string, 
/**
 * Unix time in milliseconds.
 */
sent_at: number, };
