// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BanCreate } from "./BanCreate";
import type { ChannelCreate } from "./ChannelCreate";
import type { ChannelUpdate } from "./ChannelUpdate";
import type { ChatTarget } from "./ChatTarget";
import type { ClientUpdate } from "./ClientUpdate";
import type { GroupCreate } from "./GroupCreate";
import type { GroupUpdate } from "./GroupUpdate";
import type { Hello } from "./Hello";
import type { InviteCreate } from "./InviteCreate";
import type { MemberPrune } from "./MemberPrune";
import type { ServerUpdate } from "./ServerUpdate";

/**
 * Client → server frame.
 */
export type ClientFrame = { id: number, } & ({ "op": "hello", "d": Hello } | { "op": "ping", "d": Record<symbol, never> } | { "op": "client.update", "d": ClientUpdate } | { "op": "client.move", "d": { client: number, channel: number, } } | { "op": "client.kick", "d": { client: number, reason: string | null, } } | { "op": "channel.join", "d": { channel: number, password: string | null, } } | { "op": "channel.leave", "d": Record<symbol, never> } | { "op": "channel.create", "d": ChannelCreate } | { "op": "channel.update", "d": ChannelUpdate } | { "op": "channel.delete", "d": { channel: number, } } | { "op": "chat.send", "d": { target: ChatTarget, text: string, 
/**
 * Users mentioned as `@nickname` in `text` (the text stays readable as is).
 */
mentions?: Array<string>, 
/**
 * Ids of finished uploads (see `file.upload`) to attach.
 */
attachments?: Array<string>, } } | { "op": "chat.edit", "d": { message: number, text: string, mentions?: Array<string>, } } | { "op": "chat.delete", "d": { message: number, } } | { "op": "chat.read", "d": { channel: number, message: number, } } | { "op": "chat.history", "d": { channel: number, before: number | null, limit: number | null, } } | { "op": "server.update", "d": ServerUpdate } | { "op": "token.create", "d": { group: number, } } | { "op": "file.upload", "d": { name: string, size: bigint, mime: string, } } | { "op": "group.create", "d": GroupCreate } | { "op": "group.update", "d": GroupUpdate } | { "op": "group.delete", "d": { group: number, } } | { "op": "member.nickname", "d": { uid: string, nickname: string, } } | { "op": "member.groups", "d": { uid: string, groups: Array<number>, } } | { "op": "member.remove", "d": { uid: string, delete_messages: boolean, } } | { "op": "member.prune", "d": MemberPrune } | { "op": "ban.create", "d": BanCreate } | { "op": "ban.list", "d": Record<symbol, never> } | { "op": "ban.delete", "d": { ban: number, } } | { "op": "invite.create", "d": InviteCreate } | { "op": "invite.list", "d": Record<symbol, never> } | { "op": "invite.delete", "d": { code: string, } } | { "op": "token.redeem", "d": { token: string, } } | { "op": "voice.offer", "d": { sdp: string, } });
