// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientUpdate = { nickname?: string | null, muted?: boolean | null, deafened?: boolean | null, 
/**
 * `Some("")` clears the away status.
 */
away?: string | null, };
