// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelCreate } from "./ChannelCreate";
import type { ChannelUpdate } from "./ChannelUpdate";
import type { ChatTarget } from "./ChatTarget";
import type { ClientUpdate } from "./ClientUpdate";
import type { Hello } from "./Hello";
import type { ServerUpdate } from "./ServerUpdate";

/**
 * Client → server frame.
 */
export type ClientFrame = { id: number, } & ({ "op": "hello", "d": Hello } | { "op": "ping", "d": Record<symbol, never> } | { "op": "client.update", "d": ClientUpdate } | { "op": "client.move", "d": { client: number, channel: number, } } | { "op": "client.kick", "d": { client: number, reason: string | null, } } | { "op": "channel.join", "d": { channel: number, password: string | null, } } | { "op": "channel.leave", "d": Record<symbol, never> } | { "op": "channel.create", "d": ChannelCreate } | { "op": "channel.update", "d": ChannelUpdate } | { "op": "channel.delete", "d": { channel: number, } } | { "op": "chat.send", "d": { target: ChatTarget, text: string, } } | { "op": "chat.read", "d": { channel: number, message: number, } } | { "op": "chat.history", "d": { channel: number, before: number | null, limit: number | null, } } | { "op": "server.update", "d": ServerUpdate } | { "op": "token.create", "d": { group: number, } } | { "op": "token.redeem", "d": { token: string, } } | { "op": "voice.offer", "d": { sdp: string, } });
