// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Platform } from "./Platform";

export type ClientSoftware = { name: string, version: string, platform: Platform, };
