// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Signed by the account key over
 * `gwar device v1\n{account_key}\n{device_key}\n{issued_at}\n{expires_at}` (docs/connect.md).
 */
export type DeviceCertificate = { account_key: string, device_key: string, issued_at: number, expires_at: number, signature: string, };
