// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BanNotice } from "./BanNotice";
import type { ErrorCode } from "./ErrorCode";

export type ErrorBody = { code: ErrorCode, message: string, 
/**
 * Set with [`ErrorCode::Banned`]: who, why and until when.
 */
ban?: BanNotice | null, };
