// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCode = "bad_request" | "not_authenticated" | "not_found" | "forbidden" | "wrong_password" | "channel_full" | "rate_limited" | "conflict" | "unavailable" | "internal";
