// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Challenge } from "./Challenge";
import type { Channel } from "./Channel";
import type { ChatMessage } from "./ChatMessage";
import type { Client } from "./Client";
import type { Group } from "./Group";
import type { LeaveReason } from "./LeaveReason";
import type { Member } from "./Member";
import type { ServerInfo } from "./ServerInfo";

export type Event = { "ev": "challenge", "d": Challenge } | { "ev": "server.updated", "d": ServerInfo } | { "ev": "channel.created", "d": Channel } | { "ev": "channel.updated", "d": Channel } | { "ev": "channel.deleted", "d": { channel: number, } } | { "ev": "client.joined", "d": Client } | { "ev": "client.updated", "d": Client } | { "ev": "client.left", "d": { client: number, reason: LeaveReason, } } | { "ev": "chat.message", "d": ChatMessage } | { "ev": "chat.edited", "d": ChatMessage } | { "ev": "chat.deleted", "d": { channel: number, message: number, } } | { "ev": "group.created", "d": Group } | { "ev": "group.updated", "d": Group } | { "ev": "group.deleted", "d": { group: number, } } | { "ev": "member.updated", "d": Member } | { "ev": "member.removed", "d": { uid: string, } } | { "ev": "voice.talking", "d": { client: number, talking: boolean, } } | { "ev": "voice.slot", "d": { slot: number, client: number | null, } } | { "ev": "voice.closed", "d": { reason: string, } } | { "ev": "chat.read", "d": { channel: number, message: number, } } | { "ev": "disconnected", "d": { reason: LeaveReason, } };
