// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission } from "./Permission";

/**
 * Absent fields stay unchanged; `color: ""` removes the color.
 */
export type GroupUpdate = { group: number, name?: string | null, permissions?: Array<Permission> | null, color?: string | null, };
