// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission } from "./Permission";

export type Group = { id: number, name: string, permissions: Array<Permission>, };
