// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientSoftware } from "./ClientSoftware";

export type Hello = { protocol: number, nickname: string, 
/**
 * Base64url (no padding) Ed25519 public key.
 */
public_key: string, 
/**
 * Base64url signature over `challenge_message(nonce, public_key)`.
 */
signature: string, server_password: string | null, 
/**
 * Invite code: admits without the server password and may grant a group.
 */
invite?: string | null, client: ClientSoftware, };
