// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Invite = { code: string, uses: number, max_uses?: number | null, expires_at?: number | null, group?: number | null, created_by: string, created_at: number, };
