// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InviteCreate = { max_uses?: number | null, 
/**
 * Seconds until it expires; absent means never.
 */
expires_in?: number | null, 
/**
 * Group granted to whoever joins with it.
 */
group?: number | null, };
