// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every field is required: a forgotten flag must never widen what gets removed.
 */
export type MemberPrune = { 
/**
 * Members not seen for at least this many days (1 to 3650).
 */
inactive_days: number, 
/**
 * Spare members who hold any role besides the default Member one.
 */
without_groups_only: boolean, 
/**
 * Also delete their messages and files.
 */
delete_messages: boolean, 
/**
 * Only report what would be removed.
 */
dry_run: boolean, };
