// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Member = { uid: string, nickname: string, groups: Array<number>, 
/**
 * Unix time in milliseconds.
 */
last_seen: number, };
