// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Member = { uid: string, 
/**
 * The nickname on this server (the same on every device of this member).
 */
nickname: string, 
/**
 * Shortest prefix, at least [`TAG_MIN_LEN`] characters, of the uid's bytes in
 * lowercase base32 that no other member of this server shares. Tells apart
 * members with the same nickname; it may grow when a new member collides.
 */
tag: string, 
/**
 * Handle of the Gwar Connect account this identity belongs to, as confirmed
 * by the Connect service. `None` for local identities.
 */
connect?: string | null, groups: Array<number>, 
/**
 * Unix time in milliseconds.
 */
last_seen: number, };
