// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";
import type { ChatMessage } from "./ChatMessage";
import type { Welcome } from "./Welcome";

export type Response = Welcome | Channel | ChatMessage | { messages: Array<ChatMessage>, } | { token: string, } | { groups: Array<number>, } | { sdp: string, } | Record<symbol, never>;
