// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ban } from "./Ban";
import type { Channel } from "./Channel";
import type { ChatMessage } from "./ChatMessage";
import type { Group } from "./Group";
import type { Invite } from "./Invite";
import type { Member } from "./Member";
import type { Welcome } from "./Welcome";

export type Response = Welcome | Channel | ChatMessage | { messages: Array<ChatMessage>, } | { token: string, } | { groups: Array<number>, } | { sdp: string, } | { group: Group, } | { ban: Ban, } | { bans: Array<Ban>, } | { invite: Invite, } | { invites: Array<Invite>, } | { file: string, upload_url: string, } | { uids: Array<string>, count: number, members: Array<Member>, } | Record<symbol, never>;
