// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorBody } from "./ErrorBody";
import type { Event } from "./Event";
import type { Response } from "./Response";

/**
 * Server → client frame.
 */
export type ServerFrame = { re: number, ok: Response, } | { re: number, err: ErrorBody, } | Event;
