// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Absent fields stay unchanged; `password: ""` removes the server password.
 */
export type ServerUpdate = { name?: string | null, welcome?: string | null, default_channel?: number | null, password?: string | null, max_clients?: number | null, };
