// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Unread = { channel: number, 
/**
 * Last message read; 0 if none.
 */
last_read: number, 
/**
 * Messages after `last_read`, capped at [`UNREAD_CAP`].
 */
count: number, };
